fix(commands): add -W to yarn install when in yarn workspaces root
dhis2/cli-utils-cypress pull request #121
Opened 2021-01-04 14:29 UTC by HendrikThePendric

The command `d2-utils-cypress install` would not complete successfully in a yarn workspaces repo due to the missing `-W` flag. This fixes it, but I wonder if there would be a more elegant way to do this...

2021-01-04 14:32 UTC, amcgee requested changes
@HendrikThePendric I think this will throw if `package.json` doesn't exist or isn't valid JSON, so if going with this approach it at least needs a `try/catch`

2021-01-04 14:35 UTC, HendrikThePendric commented
I did consider that, but thought I would just let the error throw in any case. If there is no package.json or it contains invalid json, this script failing is the least of the repo's worries right?

2021-01-04 14:50 UTC, amcgee commented
It could fail just because it's being run in a directory that doesn't happen to be a package root - in that case it would be much nicer to say "install must be run from the root of an npm package, but no package.json was found" rather than simply an IO failure with a nasty stack trace.

2021-01-04 14:50 UTC, amcgee commented
Technically we should find-up to the nearest package root anyway, rather than assuming the CWD is the root

2021-01-06 10:07 UTC, amcgee approved these changes
LGTM - suggested a minor update to the message

2021-01-06 11:43 UTC, merged