fix(network-shim): ensure in-test fixtures are used instead of shim fixtures
dhis2/cli-utils-cypress pull request #176
Opened 2021-04-22 14:42 UTC by HendrikThePendric

The core issue was fixed by upgrading cypress to v7, which includes the correct overriding behaviour for `cy.intercept`.
Due to the major version bump, capturing and stubbing requests stopped working, and this was fixed by passing regexes to cy.intercept instead of strings.
A new test was introduced to the network-shim example-app to assert the in-test fixtures take presidence over the networkshim fixtures.

BREAKING CHANGE: bumps cypress 1 major version, to v7

2021-05-03 09:25 UTC, HendrikThePendric commented
@Mohammer5 thanks for the additional commit. Would you like to request changes? If not, please approve so we can release this fix.

2021-05-04 14:43 UTC, Mohammer5 commented
I tested it with the sms config app and it didn't work "plug'n'play" style. Capturing seems to have worked, but during stub mode, the tests did not login successfullly:

![image](https://user-images.githubusercontent.com/10101831/117021414-9f090480-acf7-11eb-9f2e-74e1334bfc3a.png)

I had to make some adjustments to the sms config app to work with this version of the cli utils as they use cypress@7 and the sms config app still used v5 of our tool, the branch is: Prepare_network_shim

2021-05-18 09:57 UTC, Mohammer5 requested changes
The only real change requests I have are what we already discussed:

### Please add docs about the quirk with testing the `testing-network-shim-app` example app:

```
npx --no-install cypress cache clear
find ./ -iname node_modules -type d | xargs rm -r 
yarn install
```

### Add docs or a script to test the whole network shim in both example apps

2021-05-18 09:57 UTC, Mohammer5 commented on examples/platform-app/package.json
> +        "cy:stub-debug": "DEBUG=cypress:network:*,cypress:net-stubbing* d2-utils-cypress run --stub --appStart 'yarn cy:start' --serverMinorVersion 37"
Not sure if this should make it into the release, but it's not crucial functionality and not blocking any other script, so I don't have a strong opinion on this

2021-05-18 14:28 UTC, Mohammer5 approved these changes

2021-05-18 14:40 UTC, merged