fix: use upper-snake-case environment variable names
dhis2/cli-utils-cypress pull request #217
Opened 2021-06-01 12:13 UTC by HendrikThePendric

BREAKING CHANGE: all environment variables are now in `UPPER_SNAKE_CASE`, aligned with the bash convention. This means apps  will have to change their `cypress.env.json` and perhaps some scripts in `package.json`

2021-06-01 12:28 UTC, varl approved these changes
I agree profusely with adhering to this long-standing practice for environment variables names.

2021-06-01 14:15 UTC, ismay reviewed
Should we not add the `BREAKING CHANGE` label in the commit body to make sure it ends up in the changelog? Otherwise people might miss this.

2021-06-02 06:50 UTC, varl commented
@ismay good catch.

2021-06-02 07:51 UTC, Mohammer5 commented
I assumed that would be applied automatically when merging the PR, which should copy the PR's description into the merge's commit message body field?

2021-06-02 11:03 UTC, varl requested changes
I've reconsidered a bit when I was working on #218. This is slightly more nuanced than I initially thought.

There is value in keeping the operating system environment variables separate from the cypress environment variables.

See #218 to see what I mean, and refer to the Cypress docs[1] for why they support both: 

> In Cypress, "environment variables" are variables that are accessible via Cypress.env. These are not the same as OS-level environment variables. However, it is possible to set Cypress environment variables from OS-level environment variables.

[1] https://docs.cypress.io/guides/guides/environment-variables

2021-06-02 11:30 UTC, ismay commented
Yeah the reason I asked for this is because it gets confusing when you're setting cypress env vars from the OS. Which we're doing on CI. If we keep the existing approach we'll have both lower- and uppercased env vars on CI (and they'll be meaningful, cypress makes a distinction between upper and lowercased env vars).

If it were only cypress env vars I'd agree, but since we're crossing over into OS env vars I'd vote for uppercasing.

2021-06-02 12:53 UTC, HendrikThePendric commented
Closing in favour of https://github.com/dhis2/cli-utils-cypress/pull/217

2021-06-02 12:53 UTC, closed without merging